### PR TITLE
fixbug on cheatsheet

### PR DESCRIPTION
**Pull request by Martwu**
val['AXMenuItemCmdModifiers'] is a table which is contain:
    {1: cmd, 2: shift ...}
the key means index, the value means the modifiers.

### CODE REVIEW

**Comment by ashfinal** [comment]
It works! Thanks a lot. 👍

**Comment by Martwu** [comment]
But I found that all shortkey that contains up down left right etc would disappear on it. I have no idea.

**Comment by ashfinal** [comment]
@Martwu I look through Hammerspoon's docs and cheatsheet module's code, find [menuGlyphs](http://www.hammerspoon.org/docs/hs.application.html#menuGlyphs) was not handled well. That's why the arrow keys missed.

Still, I need to fully understand the cheatsheet module to make some change. That may take a while.

**Comment by Martwu** [comment]
@ashfinal  Got it.

**Pull request merged**
