### PR TITLE
Added week number to calendar

### PR DESCRIPTION
**Pull request by biocyberman**
Many people, in Europe at least, plan their year (work, vacation, appointments) by week numbers. Therefore I added week number on the calendar widget. The widget may need more styling, but let it be like that for now.

### CODE REVIEW

**Comment by ashfinal** [comment]
Thanks for your contribution!

I just give an glance at your code. Um … I guess we can insert another element to show weeknum. I will check it later.

**Comment by biocyberman** [comment]
My pleasure. Is it currently possible to add control buttons for move month forward and backward ?

**Comment by ashfinal** [comment]
Yeah, just setClickCallback for hs.drawing element. And we can even do more using hs.canvas.

But let's merge this commit first.

**Comment by ashfinal** [comment]
I will rewrite this module using hs.canvas in short time. Add control buttons for move month forward and backward.

**Pull request merged**
